server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://rm-bp1gvs3ti016zt2hpvo.mysql.rds.aliyuncs.com:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456Asd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 全局时间格式
    time-zone: GMT+8 # 指定默认时区，不然数据会出现传输变成标准时区的问题
  data:
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 1
      # 密码
      password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hjy.**.domain
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.hjy: debug
knife4j:
  enable: true
# 项目相关配置
App:
  # 名称
  name: hjy-app
  # 版本
  version: 0.0.1
#springdoc:
#  api-docs:
#    enabled: true
#    title:

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥 HS512 需要至少 512 bits（64 字节）的密钥。
  secret: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ12
  # 令牌有效期（默认3000分钟）
  expireTime: 3000