server:
  port: 8090
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://rm-bp1gvs3ti016zt2hpvo.mysql.rds.aliyuncs.com:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456Asd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 全局时间格式
    time-zone: GMT+8 # 指定默认时区，不然数据会出现传输变成标准时区的问题

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.hjy.**.domain
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.hjy: debug

# Swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  # 请求前缀
#  pathMapping: /
#  pathMapping: /dev-api